/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.dcm4che.staticwado;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
