/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.dcm4che.staticwado;

import org.dcm4che.staticwado.list.LinkedList;

import static org.dcm4che.staticwado.utilities.StringUtils.join;
import static org.dcm4che.staticwado.utilities.StringUtils.split;
import static org.dcm4che.staticwado.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class StaticWado {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
